[package]
name = "cli-image-to-ascii"
description = "A library for rendering images as truecolor ANSI terminal art"

version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
image = { version = "0.25.10", default-features = false }
