//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "book_blobs")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub tenant_id: String,
  #[sea_orm(column_type = "Text")]
  pub book_id: String,
  #[sea_orm(column_type = "Text")]
  pub storage: String,
  #[sea_orm(column_type = "Blob", nullable)]
  pub bytes: Option<Vec<u8>>,
  #[sea_orm(column_type = "Text", nullable)]
  pub path: Option<String>,
  pub byte_len: i64,
  #[sea_orm(column_type = "Text")]
  pub sha256: String,
  pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::books::Entity",
    from = "Column::BookId",
    to = "super::books::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Books,
  #[sea_orm(
    belongs_to = "super::tenants::Entity",
    from = "Column::TenantId",
    to = "super::tenants::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Tenants,
}

impl Related<super::books::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Books.def()
  }
}

impl Related<super::tenants::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tenants.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
