//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tenants")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text", unique)]
  pub slug: String,
  #[sea_orm(column_type = "Text")]
  pub name: String,
  pub disabled: i64,
  pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::api_tokens::Entity")]
  ApiTokens,
  #[sea_orm(has_many = "super::audit_log::Entity")]
  AuditLog,
  #[sea_orm(has_many = "super::book_blobs::Entity")]
  BookBlobs,
  #[sea_orm(has_many = "super::book_extractions::Entity")]
  BookExtractions,
  #[sea_orm(has_many = "super::book_tags::Entity")]
  BookTags,
  #[sea_orm(has_many = "super::bookmarks::Entity")]
  Bookmarks,
  #[sea_orm(has_many = "super::books::Entity")]
  Books,
  #[sea_orm(has_many = "super::device_book_scopes::Entity")]
  DeviceBookScopes,
  #[sea_orm(has_many = "super::devices::Entity")]
  Devices,
  #[sea_orm(has_many = "super::directories::Entity")]
  Directories,
  #[sea_orm(has_many = "super::document_permissions::Entity")]
  DocumentPermissions,
  #[sea_orm(has_many = "super::document_shares::Entity")]
  DocumentShares,
  #[sea_orm(has_many = "super::highlights::Entity")]
  Highlights,
  #[sea_orm(has_many = "super::notes::Entity")]
  Notes,
  #[sea_orm(has_many = "super::notifications::Entity")]
  Notifications,
  #[sea_orm(has_many = "super::org_group_members::Entity")]
  OrgGroupMembers,
  #[sea_orm(has_many = "super::org_groups::Entity")]
  OrgGroups,
  #[sea_orm(has_many = "super::organization_members::Entity")]
  OrganizationMembers,
  #[sea_orm(has_many = "super::organizations::Entity")]
  Organizations,
  #[sea_orm(has_many = "super::passkeys::Entity")]
  Passkeys,
  #[sea_orm(has_many = "super::progress::Entity")]
  Progress,
  #[sea_orm(has_many = "super::reading_days::Entity")]
  ReadingDays,
  #[sea_orm(has_many = "super::reading_time::Entity")]
  ReadingTime,
  #[sea_orm(has_many = "super::recovery_codes::Entity")]
  RecoveryCodes,
  #[sea_orm(has_many = "super::sessions::Entity")]
  Sessions,
  #[sea_orm(has_many = "super::tags::Entity")]
  Tags,
  #[sea_orm(has_many = "super::users::Entity")]
  Users,
}

impl Related<super::api_tokens::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::ApiTokens.def()
  }
}

impl Related<super::audit_log::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::AuditLog.def()
  }
}

impl Related<super::book_blobs::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::BookBlobs.def()
  }
}

impl Related<super::book_extractions::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::BookExtractions.def()
  }
}

impl Related<super::book_tags::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::BookTags.def()
  }
}

impl Related<super::bookmarks::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Bookmarks.def()
  }
}

impl Related<super::books::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Books.def()
  }
}

impl Related<super::device_book_scopes::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::DeviceBookScopes.def()
  }
}

impl Related<super::devices::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Devices.def()
  }
}

impl Related<super::directories::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Directories.def()
  }
}

impl Related<super::document_permissions::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::DocumentPermissions.def()
  }
}

impl Related<super::document_shares::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::DocumentShares.def()
  }
}

impl Related<super::highlights::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Highlights.def()
  }
}

impl Related<super::notes::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Notes.def()
  }
}

impl Related<super::notifications::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Notifications.def()
  }
}

impl Related<super::org_group_members::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::OrgGroupMembers.def()
  }
}

impl Related<super::org_groups::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::OrgGroups.def()
  }
}

impl Related<super::organization_members::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::OrganizationMembers.def()
  }
}

impl Related<super::organizations::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Organizations.def()
  }
}

impl Related<super::passkeys::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Passkeys.def()
  }
}

impl Related<super::progress::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Progress.def()
  }
}

impl Related<super::reading_days::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::ReadingDays.def()
  }
}

impl Related<super::reading_time::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::ReadingTime.def()
  }
}

impl Related<super::recovery_codes::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::RecoveryCodes.def()
  }
}

impl Related<super::sessions::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Sessions.def()
  }
}

impl Related<super::tags::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tags.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
