//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub tenant_id: String,
  #[sea_orm(column_type = "Text")]
  pub email: String,
  #[sea_orm(column_type = "Text")]
  pub display_name: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub password_hash: Option<String>,
  pub password_enabled: i64,
  #[sea_orm(column_type = "Text")]
  pub role: String,
  pub disabled: i64,
  pub created_at: i64,
  pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::bookmarks::Entity")]
  Bookmarks,
  #[sea_orm(has_many = "super::books::Entity")]
  Books,
  #[sea_orm(has_many = "super::devices::Entity")]
  Devices,
  #[sea_orm(has_many = "super::highlights::Entity")]
  Highlights,
  #[sea_orm(has_many = "super::notes::Entity")]
  Notes,
  #[sea_orm(has_many = "super::notifications::Entity")]
  Notifications,
  #[sea_orm(has_many = "super::org_group_members::Entity")]
  OrgGroupMembers,
  #[sea_orm(has_many = "super::organization_members::Entity")]
  OrganizationMembers,
  #[sea_orm(has_many = "super::passkeys::Entity")]
  Passkeys,
  #[sea_orm(has_many = "super::progress::Entity")]
  Progress,
  #[sea_orm(has_many = "super::reading_days::Entity")]
  ReadingDays,
  #[sea_orm(has_many = "super::reading_time::Entity")]
  ReadingTime,
  #[sea_orm(has_many = "super::recovery_codes::Entity")]
  RecoveryCodes,
  #[sea_orm(has_many = "super::sessions::Entity")]
  Sessions,
  #[sea_orm(
    belongs_to = "super::tenants::Entity",
    from = "Column::TenantId",
    to = "super::tenants::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Tenants,
}

impl Related<super::bookmarks::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Bookmarks.def()
  }
}

impl Related<super::books::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Books.def()
  }
}

impl Related<super::devices::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Devices.def()
  }
}

impl Related<super::highlights::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Highlights.def()
  }
}

impl Related<super::notes::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Notes.def()
  }
}

impl Related<super::notifications::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Notifications.def()
  }
}

impl Related<super::org_group_members::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::OrgGroupMembers.def()
  }
}

impl Related<super::organization_members::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::OrganizationMembers.def()
  }
}

impl Related<super::passkeys::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Passkeys.def()
  }
}

impl Related<super::progress::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Progress.def()
  }
}

impl Related<super::reading_days::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::ReadingDays.def()
  }
}

impl Related<super::reading_time::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::ReadingTime.def()
  }
}

impl Related<super::recovery_codes::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::RecoveryCodes.def()
  }
}

impl Related<super::sessions::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Sessions.def()
  }
}

impl Related<super::tenants::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tenants.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
