//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "api_tokens")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub tenant_id: String,
  #[sea_orm(column_type = "Text")]
  pub device_id: String,
  #[sea_orm(column_type = "Text", unique)]
  pub prefix: String,
  #[sea_orm(column_type = "Text")]
  pub token_hash: String,
  pub created_at: i64,
  pub last_used_at: Option<i64>,
  pub expires_at: Option<i64>,
  pub revoked: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::devices::Entity",
    from = "Column::DeviceId",
    to = "super::devices::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Devices,
  #[sea_orm(
    belongs_to = "super::tenants::Entity",
    from = "Column::TenantId",
    to = "super::tenants::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Tenants,
}

impl Related<super::devices::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Devices.def()
  }
}

impl Related<super::tenants::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tenants.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
