//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "audit_log")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub tenant_id: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub actor_user_id: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub actor_device_id: Option<String>,
  #[sea_orm(column_type = "Text")]
  pub action: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub target_type: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub target_id: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub metadata: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub ip: Option<String>,
  pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tenants::Entity",
    from = "Column::TenantId",
    to = "super::tenants::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Tenants,
}

impl Related<super::tenants::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tenants.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
