//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "books")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub tenant_id: String,
  #[sea_orm(column_type = "Text")]
  pub owner_user_id: String,
  #[sea_orm(column_type = "Text")]
  pub content_hash: String,
  #[sea_orm(column_type = "Text")]
  pub title: String,
  #[sea_orm(column_type = "Text")]
  pub author: String,
  #[sea_orm(column_type = "Text")]
  pub format: String,
  pub size_bytes: i64,
  pub created_at: i64,
  pub updated_at: i64,
  #[sea_orm(column_type = "Text", nullable)]
  pub organization_id: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub directory_id: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub file_name: Option<String>,
  #[sea_orm(column_type = "Text")]
  pub sync_mode: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::book_blobs::Entity")]
  BookBlobs,
  #[sea_orm(
    belongs_to = "super::tenants::Entity",
    from = "Column::TenantId",
    to = "super::tenants::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Tenants,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::OwnerUserId",
    to = "super::users::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Users,
}

impl Related<super::book_blobs::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::BookBlobs.def()
  }
}

impl Related<super::tenants::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tenants.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
