//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bookmarks")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub tenant_id: String,
  #[sea_orm(column_type = "Text")]
  pub user_id: String,
  #[sea_orm(column_type = "Text")]
  pub book_id: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub device_id: Option<String>,
  #[sea_orm(column_type = "Text")]
  pub mark: String,
  pub line: i64,
  pub col: i64,
  #[sea_orm(column_type = "Text", nullable)]
  pub op_id: Option<String>,
  pub deleted: i64,
  pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tenants::Entity",
    from = "Column::TenantId",
    to = "super::tenants::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Tenants,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::UserId",
    to = "super::users::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Users,
}

impl Related<super::tenants::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tenants.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
