//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "devices")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub tenant_id: String,
  #[sea_orm(column_type = "Text")]
  pub user_id: String,
  #[sea_orm(column_type = "Text")]
  pub name: String,
  #[sea_orm(column_type = "Text")]
  pub platform: String,
  pub read_only: i64,
  pub progress_sync_denied: i64,
  pub revoked: i64,
  pub created_at: i64,
  pub last_seen_at: Option<i64>,
  #[sea_orm(column_type = "Text")]
  pub default_access: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub machine_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::api_tokens::Entity")]
  ApiTokens,
  #[sea_orm(has_many = "super::device_book_scopes::Entity")]
  DeviceBookScopes,
  #[sea_orm(
    belongs_to = "super::tenants::Entity",
    from = "Column::TenantId",
    to = "super::tenants::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Tenants,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::UserId",
    to = "super::users::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Users,
}

impl Related<super::api_tokens::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::ApiTokens.def()
  }
}

impl Related<super::device_book_scopes::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::DeviceBookScopes.def()
  }
}

impl Related<super::tenants::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tenants.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
