//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "document_shares")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub tenant_id: String,
  #[sea_orm(column_type = "Text")]
  pub content_hash: String,
  #[sea_orm(column_type = "Text")]
  pub from_user_id: String,
  #[sea_orm(column_type = "Text")]
  pub to_user_id: String,
  #[sea_orm(column_type = "Text")]
  pub access: String,
  #[sea_orm(column_type = "Text")]
  pub status: String,
  pub created_at: i64,
  pub updated_at: i64,
  pub responded_at: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tenants::Entity",
    from = "Column::TenantId",
    to = "super::tenants::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Tenants,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::ToUserId",
    to = "super::users::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Users2,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::FromUserId",
    to = "super::users::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Users1,
}

impl Related<super::tenants::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tenants.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
