//! `SeaORM` Entity. @generated by hand in the sea-orm-codegen style.
//!
//! The public marker for an account's end-to-end encryption: whether it is on,
//! and the non-secret material (KDF id, salt, verifier) a new client needs to
//! derive the same key and confirm a typed passphrase. No key material is ever
//! stored here — the server cannot decrypt anything, by design. One row per
//! (tenant, user).

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "encryption_markers")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub tenant_id: String,
  #[sea_orm(column_type = "Text")]
  pub user_id: String,
  /// 0/1: whether encrypted uploads are required for this account.
  pub enabled: i64,
  /// Key-derivation function id, e.g. `argon2id`.
  #[sea_orm(column_type = "Text")]
  pub kdf: String,
  /// Envelope algorithm id the account was set up with.
  pub alg: i64,
  /// base64 of the per-account KDF salt (non-secret).
  #[sea_orm(column_type = "Text")]
  pub salt: String,
  /// base64 of the verifier sentinel sealed under the derived key.
  #[sea_orm(column_type = "Text")]
  pub verifier: String,
  pub created_at: i64,
  pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tenants::Entity",
    from = "Column::TenantId",
    to = "super::tenants::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Tenants,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::UserId",
    to = "super::users::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Users,
}

impl Related<super::tenants::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tenants.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
