//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "org_groups")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub tenant_id: String,
  #[sea_orm(column_type = "Text")]
  pub organization_id: String,
  #[sea_orm(column_type = "Text")]
  pub name: String,
  pub created_at: i64,
  pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::org_group_members::Entity")]
  OrgGroupMembers,
  #[sea_orm(
    belongs_to = "super::organizations::Entity",
    from = "Column::OrganizationId",
    to = "super::organizations::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Organizations,
  #[sea_orm(
    belongs_to = "super::tenants::Entity",
    from = "Column::TenantId",
    to = "super::tenants::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Tenants,
}

impl Related<super::org_group_members::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::OrgGroupMembers.def()
  }
}

impl Related<super::organizations::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Organizations.def()
  }
}

impl Related<super::tenants::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tenants.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
