//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "organizations")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub tenant_id: String,
  #[sea_orm(column_type = "Text")]
  pub name: String,
  #[sea_orm(column_type = "Text")]
  pub slug: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub created_by_user_id: Option<String>,
  pub created_at: i64,
  pub updated_at: i64,
  #[sea_orm(column_type = "Text")]
  pub default_access: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::directories::Entity")]
  Directories,
  #[sea_orm(has_many = "super::document_permissions::Entity")]
  DocumentPermissions,
  #[sea_orm(has_many = "super::org_groups::Entity")]
  OrgGroups,
  #[sea_orm(has_many = "super::organization_members::Entity")]
  OrganizationMembers,
  #[sea_orm(
    belongs_to = "super::tenants::Entity",
    from = "Column::TenantId",
    to = "super::tenants::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Tenants,
}

impl Related<super::directories::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Directories.def()
  }
}

impl Related<super::document_permissions::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::DocumentPermissions.def()
  }
}

impl Related<super::org_groups::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::OrgGroups.def()
  }
}

impl Related<super::organization_members::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::OrganizationMembers.def()
  }
}

impl Related<super::tenants::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tenants.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
